### ISSUE TITLE
[FATAL] Could not load CA key pair: open : no such file or directory

### ISSUE THREAD

**Issue by scalefree** [dstotijn/hetty#12]
Just tried running on Ubuntu 20.04, no dice.

[FATAL] Could not load CA key pair: open : no such file or directory

**Comment by jg4git** [comment]
same on win_x64 

2020/09/28 10:53:55 [FATAL] Could not load CA key pair: open : The system cannot
 find the file specified.

are we looking for some environment data?

**Comment by al-madjus** [comment]
First create a cert and key with
`openssl req -newkey rsa:2048 -new -nodes -x509 -days 365 -keyout key.pem -out cert.pem`

Then run Hetty with
`./hetty -key key.pem -cert cert.pem`

(You might of course need to specify the path to the key and cert files)

**Comment by scalefree** [comment]
OK, making progress.  Initially I just ran hetty by itself & got the key error.  Took al-madjus's advice & made keys & ran hetty again pointing to them.  Got further:

./hetty -key ./key.pem -cert ./cert.pem
2020/09/28 11:36:35 [INFO] Running server on :80 ...
2020/09/28 11:36:35 [FATAL] HTTP server closed: listen tcp :80: bind: permission denied

Since only root can connect to low ports I reran with sudo.  Got even further but not quite far enough:

sudo ./hetty -key ./key.pem -cert ./cert.pem
2020/09/28 11:36:49 [INFO] Running server on :80 ...
2020/09/28 11:37:05 [ERROR]: Proxy error: dial tcp 127.0.0.1:443: connect: connection refused
2020/09/28 11:37:05 [ERROR]: Proxy error: dial tcp 127.0.0.1:443: connect: connection refused

I could connect to a server at localhost:80 but nothing displayed, logs show a 502 error & hetty's STDERR showed this:

2020/09/28 11:37:05 [ERROR]: Proxy error: dial tcp 127.0.0.1:443: connect: connection refused

I have no proxies running so that's from hetty.  That's as far as I got.

**Comment by Ahsan-x** [comment]
I'm getting the same issue can anyone help

**Comment by RiRa12621** [comment]
Low ports require root permissions.
Please try to listen to a different port to mitigate the first problem.

I'll try to replicate the second one as well later tonight or tomorrow.

**Comment by scalefree** [comment]
FWIW I finally looked at the help:

./hetty -h
Usage of ./hetty:
  -addr string
        TCP address to listen on, in the form "host:port" (default ":80")
  -adminPath string
        File path to admin build
  -cert string
        CA certificate file path
  -db string
        Database file path (default "hetty.db")
  -key string
        CA private key file path

**Comment by RiRa12621** [comment]
So if you specify everything correctly it works?

**Comment by scalefree** [comment]
It doesn't crash at least, yes.  No UI or anything usable yet though.  Firefox gives me a blank page & tries & fails to forward to 443.

**Comment by RiRa12621** [comment]
can you explicitly specify the address like `-addr 127.0.0.1:8080` ?
Please note that I'm using a port that doesn't require privilege.
That should mitigate your problem.
Still a bug, trying to chase that down but at least it should work like that

**Comment by scalefree** [comment]
It mitigates that problem, yes.  But I still get no UI just a new error.  Running Firefox 81.0 on Ubuntu 20.04.

`./hetty -addr localhost:9876 -key ./key.pem -cert ./cert.pem`

`2020/09/28 14:21:33 [INFO] Running server on localhost:9876 ...
2020/09/28 14:21:44 [ERROR]: Proxy error: tls: first record does not look like a TLS handshake
2020/09/28 14:21:45 [ERROR]: Proxy error: tls: first record does not look like a TLS handshake`

**Comment by RiRa12621** [comment]
@dstotijn something weird is happening in the proxy library
```
$ go run cmd/hetty/main.go -key hetty_key.pem -cert hetty_cert.pem -addr 127.0.0.1:443
2020/09/28 20:29:27 [INFO] Running server on 127.0.0.1:443 ...
2020/09/28 20:29:27 [FATAL] HTTP server closed: listen tcp 127.0.0.1:443: bind: permission denied
exit status 1
```

```
$ sudo go run cmd/hetty/main.go -key hetty_key.pem -cert hetty_cert.pem -addr 127.0.0.1:443
Password:
2020/09/28 20:29:41 [INFO] Running server on 127.0.0.1:443 ...
2020/09/28 20:29:44 [ERROR]: Proxy error: tls: first record does not look like a TLS handshake
2020/09/28 20:29:44 [ERROR]: Proxy error: tls: first record does not look like a TLS handshake
```
```
$ sudo go run cmd/hetty/main.go -key hetty_key.pem -cert hetty_cert.pem -addr 127.0.0.1:8080
2020/09/28 20:30:27 [INFO] Running server on 127.0.0.1:8080 ...
```

**Comment by dstotijn** [comment]
Hi everybody, just pushed a few commits that should make things easier:
* By default, `hetty` now binds on `:8080`
* You can omit the `-key` and `-cert` params if you want, and Hetty will by default create them in `~/.hetty/hetty_key.pem` and `~/.hetty/hetty_cert.pem` respectively.

You need to add `~/.hetty/hetty_cert.pem` to your CA root store. I'll add instructions later in the docs, but for now please Google "import ca certificate".

Please let me know how things go!

**Comment by scalefree** [comment]
Still using original binary, added keys to system & firefox.  No more errors but still no UI.

**Comment by dstotijn** [comment]
> Still using original binary, added keys to system & firefox. No more errors but still no UI.

Did you built from source (e.g. `go get`)? In that case you also have to manually export and bundle the admin UI. See the note in the README about `make build`. Alternatively, you could grab a download from the [releases](https://github.com/dstotijn/hetty/releases/tag/v0.1.0) page; it already has the admin built in.

**Comment by scalefree** [comment]
I grabbed the prebuilt binary. If there's a new release I'll grab that.  Thanks.

**Comment by scalefree** [comment]
OK, release 0.1.1, using prebuilt binary.  When I ran it some weird folders were created - one named '~', another inside that named hetty & a file inside that named hetty.bolt.

**Comment by RiRa12621** [comment]
That behavior should be a separate issue imho.
That doesn't seem related

**Comment by dstotijn** [comment]
>OK, release 0.1.1, using prebuilt binary. When I ran it some weird folders were created - one named '~', another inside that named hetty & a file inside that named hetty.bolt.

> That behavior should be a separate issue imho.
> That doesn't seem related

Ah weird; on my macOS system the expansion of `~` worked for the DB path, but maybe not for other archs. Just rolled another release (`v0.1.2`) that should fix it.

**Comment by scalefree** [comment]
Success!  I have UI!

`Hetty://
The simple HTTP toolkit for security research.`

**Comment by dstotijn** [comment]
> Success! I have UI!
> 
> `Hetty:// The simple HTTP toolkit for security research.`

You're running Ubuntu 20.04, right?
This should work to get the MITM CA cert added to your store, assuming you started the latest release without any parameters set:

```
$ sudo cp ~/.hetty/hetty_cert.pem /usr/local/share/ca-certificates/hetty.crt
$ sudo update-ca-certificates
```

Then you should be able to configure your system (or browser, e.g. via FoxyProxy or something) to use `localhost:8080` as the HTTP proxy address. If you then incur HTTP traffic, you should see it on http://localhost:8080/proxy/logs.

**Comment by tcarrio** [comment]
Is this something that might be useful to have automated as part of the CLI? Generating the certificate and based on the OS pushing to a location on the host and updating certs?

I think the x crypto libs may include everything needed to build into the binary even.

**Comment by dstotijn** [comment]
> Is this something that might be useful to have automated as part of the CLI? Generating the certificate and based on the OS pushing to a location on the host and updating certs?
> 
> I think the x crypto libs may include everything needed to build into the binary even.

IMHO, Hetty shouldn't automatically push/copy any certificates to the local root CA store, but I'll (eventually) look into a way to make it opt-in. Probably via a CLI flag but also through a "Proxy setup" page in the web interface. Given that Firefox (by default) uses its own root CA store, we could leverage the default paths ([ref](https://wiki.mozilla.org/CA/AddRootToFirefox#Import_via_Policy)) it uses and copy/symlink to those directories.

Closing this for now, pending write-up in future roadmap/proposal.
