### ISSUE TITLE
Exclude assets from database.

### ISSUE THREAD

**Issue by ubogdan** [dstotijn/hetty#18]
**Is your feature request related to a problem? Please describe.**
Running the proxy for 30 minutes I got a 25MB database and the API started to be visible slower (3-5 seconds reported by Chrome Developer tool) ...
```
-rw-r--r--  1 bogdan bogdan  25M Sep 28 21:48 hetty.db
```

**Describe the solution you'd like**
The proxy should have a list of predefined content-types or file extensions that it should avoid storing in the history log  (at least the response body). 
example : js | css | png | jpg | gif | ico | ttf | woff | woff2

**Comment by dstotijn** [comment]
Yes, indeed!
The solution is probably twofold:
1. Add scope feature (to prevent reqs from even being logged) and also filter options for the proxy log ([ref](https://github.com/dstotijn/hetty/issues/5)). I'll add an issue for this soon.
2. Improve queries ([ref](https://github.com/dstotijn/hetty/issues/5)).

Closing this issue, please feel free to subscribe/track the above ones. I'll soon switch to writing PRs so there's room to discuss details and review before it's actually implemented. Thanks for flagging this already!
