### ISSUE TITLE
Display parsed request query params

### ISSUE THREAD

**Issue by alessio-perugini** [dstotijn/hetty#31]
**Is your feature request related to a problem? Please describe.**
It would be nice to have all the query parameters/URLEncodedForm listed in a separate box. In this way you can see immediatly what you are sending.

**Describe the solution you'd like**
A box under the current  request one would be fine.

**Describe alternatives you've considered**
Another option could be to make a sort of drop down like behaviour that displays all the paramer sent in a coincise way.

**Additional context**
![image](https://i.ibb.co/Sy4QJsN/scan.png)

After this box make something like mitmproxy
![image](https://i.ibb.co/pdhzB60/example1.png)
![image](https://i.ibb.co/4pzg6fb/example2.png)

Anyway nice project

**Comment by dstotijn** [comment]
Hi @alessio-perugini, yes indeed having a list/table of parsed (and URL decoded) query params make sense. Adding this to the backlog.

**Comment by dstotijn** [comment]
Fixed in `v0.5.0`.
