### ISSUE TITLE
httpcert error

### ISSUE THREAD

**Issue by shelu16** [dstotijn/hetty#34]
root1@SBCMUMNB76:~/tools/alltest$ hetty
2020/10/08 18:11:59 [INFO] Running server on :8080 ...
2020/10/08 18:12:34 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:39 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:40 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:41 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:41 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:42 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:42 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:43 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:43 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:46 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:49 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:13:55 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:19:05 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate
2020/10/08 18:19:06 [ERROR] Securing client connection failed: handshake error: remote error: tls: bad certificate

there is cert error how to solve i am using binary

**Comment by RiRa12621** [comment]
Which build version of hetty are you running?
