### ISSUE TITLE
Enlarge proxy request list

### ISSUE THREAD

**Issue by tati1206** [dstotijn/hetty#39]
**Is your feature request related to a problem? Please describe.**
When I'm looking at the proxy request list, I can't enlarge the list and see more requests.

**Describe the solution you'd like**
I would like that in the request list there is a slider or something to be able to enlarge the window.

**Comment by dstotijn** [comment]
Yes, good call. Please check/subscribe to https://github.com/dstotijn/hetty/issues/42
