### ISSUE TITLE
Getting error using GO111MODULE=auto go get -u -v github.com/dstotijn/hetty/cmd/hetty

### ISSUE THREAD

**Issue by Ahsan-x** [dstotijn/hetty#44]
![image](https://user-images.githubusercontent.com/46222314/97636113-5b88c180-1a5a-11eb-8cf1-064e8eebb0a5.png)

**go version go1.15.2 linux/amd64**
**Operating System = Linux Mint 20**

**Comment by dstotijn** [comment]
Hi @Ahsan-x, for now the project is not go gettable as it needs compilation of a sqlite extension written in C. Advice is to download a release for Linux from the releases page. I'll update the README with better instructions soon.

**Comment by Ahsan-x** [comment]
Thankyou! for the fast response understand it
