### ISSUE TITLE
Remove all project logs

### ISSUE THREAD

**Issue by MichalZalecki** [dstotijn/hetty#48]
**Is your feature request related to a problem? Please describe.**
Each time I run hetty the log records are persisted and over time it slows down the UI significantly. 

**Describe the solution you'd like**
I want to have a button, next to the search field, that allows me to clear all logs that are currently in the active project.

**Additional context**
I'm happy to work on it but before I start I would like to hear your thoughts @dstotijn to not waste time on a closed PR.

PS. Contribution Guidelines mention using labels but editing labels is disabled.

**Comment by dstotijn** [comment]
Yep, agree this is a desired feature. I'd say initially we can make an ad-hoc `clearHttpRequestLogs` mutation in the GraphQL server, and call that from the proxy logs overview page. I haven't thought yet about the UI/UX for generic operations on the proxy logs, but feel to propose something. Can be a single button near the search box for now, and we can refactor into something else if we add more proxy log operations later on.

Side note: I want to work soon on (cursor based) pagination (with behaviour to auto load more on scroll), so we don't constantly have to fetch all the request logs. That should also improve the overall experience (latency, amount of mounted components, etc.). Additionally, there some more performant table components for Material UI we can look into.

**Comment by MichalZalecki** [comment]
@dstotijn Great to hear that and thank you for the guidance!

**Comment by dstotijn** [comment]
👍 Also good to mention: Don't hesitate to drop by in the [Discord server](https://discord.gg/3HVsj5pTFP) if you ever want to ask/brainstorm about implementation
