### ISSUE TITLE
Hetty urldecodes request before displaying.

### ISSUE THREAD

**Issue by Sh1Yo** [dstotijn/hetty#56]
**To Reproduce**
1. curl "https://httpbin.org/get?something=somet%22ing" -x localhost:8080 -k'
2. See `GET /get?something=somet"ing HTTP/1.1` in logs.

**Expected behavior**
Do not do such transformations before displaying. 

**Desktop (please complete the following information):**
 - OS: Linux arch 5.9.9-arch1-1 #1 SMP PREEMPT Wed, 18 Nov 2020 19:52:04 +0000 x86_64 GNU/Linux

**Additional context**
As a developer, I want to see the raw request because sometimes it is matters whether the payload was urlencoded or not. If it is not a bug but an intentional transformation - add a setting that can disable this behavior.

**Comment by dstotijn** [comment]
👍 
Closing, will be part of https://github.com/dstotijn/hetty/issues/31
