### ISSUE TITLE
Feature Request: Append/Prepend Headers/Cookies

### ISSUE THREAD

**Issue by uBadRequest** [dstotijn/hetty#7]
For requests being received and sent, the ability to remove/drop/edit headers/cookies would be an awesome feature to have!

**Comment by dstotijn** [comment]
Yes, indeed! There's [a card](https://github.com/dstotijn/hetty/projects/1#card-46268307) on the project board, and I'll convert these to GH issues soon. For now going to close this issue, but check the board and issues later; this feature is one of my top priorities.
