### ISSUE TITLE
automated installing of a root CA to your local OS or browser trust store

### ISSUE THREAD

**Issue by gedw99** [dstotijn/hetty#93]
**Is your feature request related to a problem? Please describe.**

An easy way to automate the creation and installation of local ztLS so that https works for all OS and browsers you have installed.

**Describe the solution you'd like**

Golang based and reproducibility using the golang tool called mkcdrt from the security researcher that works at google.

https://github.com/FiloSottile/mkcert

**Describe alternatives you've considered**

None . I find mkcert to work very well. 

**Additional context**

**Comment by dstotijn** [comment]
Fixed in [v0.6.0](https://github.com/dstotijn/hetty/releases/tag/v0.6.0). See: https://hetty.xyz/docs/guides/trust-root-ca for usage instructions.
